// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:aw_flutter/src/rust/excel/data.dart';
import 'package:aw_flutter/src/rust/frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<ParsedExcelFile> parseExcelFile({required String filePath}) => RustLib
    .instance
    .api
    .crateApiExcelInterfaceParseExcelFile(filePath: filePath);

Future<void> writeExcelFile({
  required String filePath,
  required ExportedData exportedTables,
}) => RustLib.instance.api.crateApiExcelInterfaceWriteExcelFile(
  filePath: filePath,
  exportedTables: exportedTables,
);
